import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { loadCatalog, normalizeVerdicts, validateVerdicts } from './catalog.mjs';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const DIST = join(ROOT, 'dist');
const { items, errors } = await loadCatalog(ROOT);
if (errors.length) throw new Error(errors.join('\n'));

const verdicts = normalizeVerdicts(JSON.parse(await readFile(join(ROOT, 'verdicts.json'), 'utf8')));
const verdictErrors = validateVerdicts(verdicts, new Set(items.map((item) => item.id)));
if (verdictErrors.length) throw new Error(verdictErrors.join('\n'));

const adopted = items.filter((item) => verdicts.marks[item.id]?.state === 'star');
const cssParts = [
  '/* Generated by npm run export. Do not edit directly. */',
  `/* Adopted experiments: ${adopted.length} */`,
];
for (const item of adopted) {
  cssParts.push(`\n/* ${item.id} — ${item.title} */`);
  cssParts.push(await readFile(join(ROOT, 'experiments', item.id, 'anim.css'), 'utf8'));
}

await mkdir(DIST, { recursive: true });
await writeFile(join(ROOT, 'catalog.json'), `${JSON.stringify(items, null, 2)}\n`);
await writeFile(join(DIST, 'adopted.css'), `${cssParts.join('\n')}\n`);
await writeFile(join(DIST, 'manifest.json'), `${JSON.stringify({
  generatedAt: verdicts.updatedAt,
  sourceVerdictsUpdatedAt: verdicts.updatedAt,
  adopted: adopted.map(({ id, title, axes }) => ({ id, title, axes })),
}, null, 2)}\n`);

console.log(`exported catalog.json (${items.length}) and dist/adopted.css (${adopted.length})`);
